server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: cambio-service
        uri: lb://cambio-service
        predicates:
        - Path=/cambio-service/**
        filters:
            - RewritePath=/cursoMicro/cambio-service/(?<path>.*), /$\{path}
            - RewritePath=/cambio-service/(?<path>.*), /$\{path}
            
      - id: book-service
        uri: lb://book-service
        predicates:
        - Path=/book-service/**  
        filters:
            - RewritePath=/cursoMicro/book-service/(?<path>.*), /$\{path}
            - RewritePath=/book-service/(?<path>.*), /$\{path}     
      - id: openapi
        uri: lb://api-gateway
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type:
      - w3c
    baggage:
      enabled: true
    enabled: true


        