server:
  port: 8888
spring:
  application:
    name: tkzi-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/TKZI/tkzi-configuration-server.git
          search-paths:
          - 'greeting-service'
          